#!/bin/bash

yum install python-pip -y
pip install virtualenv
pip install --upgrade pip
   
# setting up the django environment
mkdir /opt/myproject
cd /opt/myproject
virtualenv myprojectenv
source myprojectenv/bin/activate
pip install django psycopg2
django-admin.py startproject myproject .
   
# these commands are just for visual effect
   # yum install tree -y
   # tree myproject
   
cd ..
#this finds this file and return the path to you.     ex. find / -name "settings.py" 
vim /opt/myproject/myproject/settings.py

#comment out the current DATABASE part and paste the new information  
#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
 #   }
#}

#this following line must be inserted into the settings.py file either manually or thru echo. 
#enter this into the settings.py file and edit it
echo "DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'myproject',
        'USER': 'myprojectuser',
        'PASSWORD': 'password',
        'HOST': '10.142.0.6',
        'PORT': '5432',
    }
} > /opt/myproject/myproject/settings.py

#change the host, port, password. 
#host would be the internal ip for your postgress
#port is 5432
#enter the password you created for the Postgress server. 
