#!/bin/bash

gcloud init
1
"intense-reason-191902"

yum install wget -y
https://raw.githubusercontent.com/carlosaguilar1928/NTI-310/master/postgressql-server
https://raw.githubusercontent.com/carlosaguilar1928/NTI-310/master/django-for-postgress

bash postgressql-server

djangoip=$(gcloud compute instances list | grep postgres | awk '{print $4}')
#gets ip from postgress server

bash django-for-postgress
