#!/bin/bash

export DEBIAN_FRONTEND=noninteractive

apt-get install -y  libpam-ldap nscd 
# install the debconf-utils GUI 

wget https://raw.githubusercontent.com/carlosaguilar1928/Monitoring-/master/ldap_debconf
# wget the raw ldap_debconf configuration files that were extrapolated from the manual configuration

while read line; do echo "$line" | debconf-set-selections; done < ldap_debconf

sed -i 's/compat/compat ldap/g' /etc/nsswitch.conf 

/etc/init.d/nscd restart

sed -i 's,uri ldapi:///,uri ldap://10.142.0.2,g' /etc/ldap.conf
sed -i 's/base dc=example,dc=net/base dc=nti310,dc=local/g' /etc/ldap.conf

export DEBIAN_FRONTEND=interactive
# this variable turns on/off the "ncurses" GUI from debconf
